# Generated by Django 4.0.2 on 2022-03-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-no_entrada_doc'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='documento',
            name='dirigido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.direcciones', verbose_name='Dirigido a:'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='f_entrada_doc',
            field=models.DateField(verbose_name='fecha entrada'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='f_salida_doc',
            field=models.DateField(blank=True, null=True, verbose_name='fecha salida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='no_entrada_doc',
            field=models.IntegerField(unique=True, verbose_name='Número de entrada'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='no_salida_doc',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número de salida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='t_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.tipodocumento', verbose_name='Tipo de documento'),
        ),
    ]
