# Generated by Django 4.0.2 on 2022-05-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0006_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_registro', models.IntegerField(unique=True)),
                ('no_entrada', models.IntegerField(blank=True, null=True)),
                ('f_entrada_registro', models.DateField(verbose_name='fecha entrada')),
                ('titulo', models.CharField(max_length=255)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.entidad')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.organismo')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.provincia')),
                ('t_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.tipodocumento', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Entrada a Registro',
                'verbose_name_plural': 'Entradas de Registro',
            },
        ),
    ]
