# Generated by Django 4.0.2 on 2022-05-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_documento_options_and_more'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidasRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_salida_registro', models.IntegerField(unique=True, verbose_name='Número de salida registro')),
                ('f_salida_registro', models.DateField(verbose_name='fecha de salida registro')),
                ('titulo', models.CharField(max_length=255)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.entidad')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.organismo')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.provincia')),
                ('t_documento_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.tipodocumentosalida', verbose_name='Tipo de documento de saalida')),
            ],
            options={
                'verbose_name': 'Salida de registro',
                'verbose_name_plural': 'Salidas de documentos en registro',
            },
        ),
    ]
